const { test } = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { randomUUID } = require('node:crypto');

// Explicit opt-in; never read production connection strings or credentials.
const enabled = process.env.QUOTE_RACE_DB_PORT === '55439';
const binary = process.env.QUOTE_RACE_PSQL || 'C:/Program Files/PostgreSQL/15/bin/psql.exe';
function query(sql, onData) {
  return new Promise((resolve, reject) => {
    const child = spawn(binary, ['-X', '-q', '-t', '-A', '-h', '127.0.0.1', '-p', '55439', '-U', 'postgres', '-d', 'postgres', '-v', 'ON_ERROR_STOP=1'], { windowsHide: true });
    let stdout = '', stderr = '';
    child.stdout.on('data', data => { stdout += data; onData?.(String(data)); });
    child.stderr.on('data', data => { stderr += data; });
    child.on('error', reject);
    child.on('close', code => resolve({ code, stdout: stdout.trim(), stderr }));
    child.stdin.end(`set statement_timeout = '10s';\n${sql}`);
  });
}
async function successful(sql) {
  const result = await query(sql);
  assert.equal(result.code, 0, result.stderr);
  return result.stdout;
}
function reserve(id) {
  return `select public.reserve_booking_quote('${id}',repeat('a',64),'{"name":"Synthetic race tester","email":"quote-race@example.invalid"}',true)->>'id';`;
}
async function contended(firstId, secondId) {
  let signal;
  const ready = new Promise(resolve => { signal = resolve; });
  const first = query(`begin; ${reserve(firstId)} select 'LOCK_HELD'; select pg_sleep(1); commit;`, chunk => {
    if (chunk.includes('LOCK_HELD')) signal();
  });
  // Do not wait indefinitely if the fixture/query fails before lock acquisition.
  await Promise.race([ready, first.then(result => { if (result.code !== 0) throw new Error(result.stderr); })]);
  const second = query(reserve(secondId));
  return Promise.all([first, second]);
}

test('isolated PostgreSQL serialises same-quote retries and overlapping different quotes', { skip: !enabled, timeout: 30000 }, async () => {
  const laneA = randomUUID(), laneB = randomUUID();
  const quoteA = randomUUID(), quoteB = randomUUID(), quoteC = randomUUID();
  const ids = [quoteA, quoteB, quoteC].map(id => `'${id}'`).join(',');
  try {
    await successful(`begin;
      insert into public.resources(id,name,type,active) values
        ('${laneA}','SYNTHETIC QUOTE RACE A','lane',true),('${laneB}','SYNTHETIC QUOTE RACE B','lane',true);
      with configuration as (select jsonb_build_object(
        'resources',(select coalesce(jsonb_agg(r order by id),'[]'::jsonb) from public.resources r),
        'resource_availability_rules',(select coalesce(jsonb_agg(r order by id),'[]'::jsonb) from public.resource_availability_rules r),
        'pricing_rules',(select coalesce(jsonb_agg(r order by id),'[]'::jsonb) from public.pricing_rules r),
        'slot_overrides',(select coalesce(jsonb_agg(r order by id),'[]'::jsonb) from public.slot_overrides r),
        'blocked_slots',(select coalesce(jsonb_agg(r order by id),'[]'::jsonb) from public.blocked_slots r)) value),
      fixtures(id,lane) as (values ('${quoteA}'::uuid,'${laneA}'),('${quoteB}'::uuid,'${laneB}'),('${quoteC}'::uuid,'${laneB}'))
      insert into public.booking_quotes(id,capability_hash,input,snapshot,configuration,amount_pence,expires_at)
      select fixtures.id,repeat('a',64),jsonb_build_object('serviceType','lane_hire','bookingDate',(current_date+3)::text),
        jsonb_build_object('resourceId',lane,'pricingResourceId',lane,'startAt',date_trunc('day',now())+interval '3 days 15 hours','endAt',date_trunc('day',now())+interval '3 days 17 hours','bufferMinutes',15),
        configuration.value,4000,now()+interval '10 minutes' from fixtures cross join configuration;
      commit;`);

    const [sameFirst, sameSecond] = await contended(quoteA, quoteA);
    assert.equal(sameFirst.code, 0, sameFirst.stderr);
    assert.equal(sameSecond.code, 0, sameSecond.stderr);
    assert.equal(sameFirst.stdout.split('\n')[0].trim(), sameSecond.stdout.trim(), 'both connections return the same booking ID');
    assert.equal(await successful(`select count(*) from public.bookings where quote_id='${quoteA}';`), '1');

    const [overlapFirst, overlapSecond] = await contended(quoteB, quoteC);
    assert.equal(overlapFirst.code, 0, overlapFirst.stderr);
    assert.notEqual(overlapSecond.code, 0, 'overlapping competing quote must fail');
    assert.match(overlapSecond.stderr, /Time is unavailable|Booking inventory conflict/);
    assert.equal(await successful(`select count(*) from public.bookings where quote_id in ('${quoteB}','${quoteC}');`), '1');
  } finally {
    // Delete only IDs generated by this test. No existing customer or configuration rows.
    await successful(`begin;
      delete from public.bookings where quote_id in (${ids});
      delete from public.booking_quotes where id in (${ids});
      delete from public.resources where id in ('${laneA}','${laneB}');
      commit;`);
    assert.equal(await successful(`select count(*) from public.booking_quotes where id in (${ids});`), '0');
  }
});
